import { test, expect, type Page } from '@playwright/test'

async function setSlider(page: Page, name: string, steps: number) {
  const slider = page.getByRole('slider', { name, exact: true })
  await slider.focus()
  await slider.press('Home')
  for (let index = 0; index < steps; index++) await slider.press('ArrowRight')
}

test.beforeEach(async ({ page }) => { await page.clock.setFixedTime(new Date('2026-08-19T12:00:00Z')) })

test('complete judging flow, chart, goals, validation and reset', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.goto('/')
  await page.getByRole('button', { name: 'Try Alex’s demo' }).click()
  await expect(page.getByRole('heading', { name: /Alex’s financial sandbox/ })).toBeVisible()
  await expect(page.getByTestId('baseline-ending')).toHaveText('$1,050')
  await expect(page.getByTestId('scenario-ending')).toHaveText('$1,050')
  await expect(page.locator('.recharts-line-curve')).toHaveCount(1)
  const baselinePath = await page.locator('.recharts-line-curve').first().getAttribute('d')
  expect(baselinePath).toContain('M')
  await page.screenshot({ path: '.verification/dashboard-baseline.png', fullPage: true })
  await setSlider(page, 'Dining', 14)
  await expect(page.getByTestId('scenario-ending')).toHaveText('$1,518')
  await setSlider(page, 'Subscriptions', 12)
  await page.getByLabel('Monthly income change ($)', { exact: true }).fill('150')
  await expect(page.getByTestId('scenario-ending')).toHaveText('$2,550')
  await page.getByRole('button', { name: 'Add to scenario' }).click()
  await expect(page.getByTestId('scenario-ending')).toHaveText('$1,850')
  await expect(page.getByTestId('baseline-ending')).toHaveText('$1,050')
  await expect(page.getByTestId('net-impact')).toHaveText('+$800')
  await expect(page.getByTestId('breakdown-total')).toHaveText('+$800')
  await expect(page.locator('.recharts-line-curve')).toHaveCount(2)
  await page.getByText('View monthly forecast', { exact: true }).click()
  const table = page.getByRole('table')
  await expect(table.getByRole('row', { name: /October 2026/ })).toContainText('$1,450')
  await expect(table.getByRole('row', { name: /November 2026/ })).toContainText('$1,025')
  await expect(table.getByRole('row', { name: /February 2027/ })).toContainText('$1,850')
  await page.getByText('View monthly forecast', { exact: true }).click()
  await expect(page.getByText('$150 short', { exact: true })).toBeVisible()
  await page.getByLabel('Target savings ($)').fill('1500')
  await expect(page.getByText(/You’re projected to beat this goal by/)).toContainText('$350')
  await page.getByLabel('Target savings ($)').fill('2000')
  await page.screenshot({ path: '.verification/dashboard-scenario.png', fullPage: true })
  await page.getByLabel('Amount ($)', { exact: true }).fill('-10')
  await page.getByRole('button', { name: 'Update expense' }).click()
  await expect(page.getByRole('alert')).toHaveText('Enter an amount from $0 to $1,000,000.')
  await expect(page.getByTestId('scenario-ending')).toHaveText('$1,850')
  await page.getByRole('button', { name: 'Remove one-time expense' }).click()
  await expect(page.getByTestId('scenario-ending')).toHaveText('$2,550')
  await page.getByRole('button', { name: 'Reset scenario' }).click()
  await expect(page.getByTestId('scenario-ending')).toHaveText('$1,050')
  await expect(page.getByRole('slider', { name: 'Dining', exact: true })).toHaveValue('0')
  await expect(page.getByRole('slider', { name: 'Subscriptions', exact: true })).toHaveValue('0')
  await expect(page.getByRole('slider', { name: 'Change monthly income', exact: true })).toHaveValue('0')
  await expect(page.locator('.recharts-line-curve')).toHaveCount(1)
  await expect(page.locator('.recharts-line-curve')).toHaveAttribute('d', baselinePath!)
  expect(errors).toEqual([])
})

test('mobile layout and very large negative scenario remain usable', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await page.getByRole('button', { name: 'Try Alex’s demo' }).click()
  await page.getByLabel('Amount ($)', { exact: true }).fill('1000000')
  await page.getByRole('button', { name: 'Add to scenario' }).click()
  await expect(page.getByTestId('scenario-ending')).toHaveText('-$998,950')
  await expect(page.getByText(/This scenario dips below/)).toBeVisible()
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)
  expect(overflow).toBe(false)
  await page.screenshot({ path: '.verification/dashboard-mobile-negative.png', fullPage: true })
  await page.getByRole('button', { name: 'Reset scenario' }).click()
  await expect(page.getByTestId('scenario-ending')).toHaveText('$1,050')
  await page.screenshot({ path: '.verification/dashboard-mobile.png', fullPage: true })
})

test('personal setup, signed sliders, saved baseline editing, and start over', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error' || message.type() === 'warning') errors.push(message.text()) })
  await page.goto('/')
  await page.screenshot({ path: '.verification/setup-name.png', fullPage: true })
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('alert')).toBeVisible()
  await page.getByLabel('Your name').fill('Sam')
  await page.getByRole('button', { name: 'Continue' }).click()
  await page.getByLabel('Monthly take-home income ($)').fill('2000')
  await page.getByLabel('Current savings ($)').fill('500')
  await page.getByRole('button', { name: 'Continue' }).click()
  const spending = { Housing: '1000', Groceries: '200', Dining: '100', Transportation: '100', Subscriptions: '50', Entertainment: '50', Shopping: '100', Other: '0' }
  for (const [category, amount] of Object.entries(spending)) await page.getByLabel(`${category} ($)`, { exact: true }).fill(amount)
  await page.screenshot({ path: '.verification/setup-spending.png', fullPage: true })
  await page.getByRole('button', { name: 'Continue' }).click()
  await expect(page.getByRole('heading', { name: 'Sam’s starting point' })).toBeVisible()
  await page.getByRole('button', { name: 'Open my sandbox' }).click()
  await expect(page.getByRole('heading', { name: /Sam’s financial sandbox/ })).toBeVisible()
  await expect(page.getByTestId('baseline-ending')).toHaveText('$2,900')
  await setSlider(page, 'Dining', 24)
  await expect(page.getByTestId('scenario-ending')).toHaveText('$2,780')
  await page.getByLabel('Monthly income change ($)', { exact: true }).fill('-100')
  await expect(page.getByTestId('scenario-ending')).toHaveText('$2,180')
  await expect(page.getByTestId('breakdown-total')).toHaveText('-$720')
  await page.getByRole('button', { name: 'Edit profile & baseline' }).click()
  await page.getByLabel('Your name').fill('Ignored')
  await page.getByRole('button', { name: 'Cancel' }).click()
  await expect(page.getByRole('heading', { name: /Sam’s financial sandbox/ })).toBeVisible()
  await expect(page.locator('.recharts-line-curve')).toHaveCount(2)
  await page.getByRole('button', { name: 'Edit profile & baseline' }).click()
  await page.getByLabel('Your name').fill('Taylor')
  await page.getByLabel('Housing ($)').fill('900')
  await page.getByRole('button', { name: 'Save changes' }).click()
  await expect(page.getByRole('heading', { name: /Taylor’s financial sandbox/ })).toBeVisible()
  await expect(page.getByTestId('baseline-ending')).toHaveText('$3,500')
  await expect(page.getByTestId('scenario-ending')).toHaveText('$2,780')
  await page.screenshot({ path: '.verification/personal-dashboard.png', fullPage: true })
  await page.reload()
  await expect(page.getByRole('heading', { name: /Taylor’s financial sandbox/ })).toBeVisible()
  await expect(page.getByTestId('scenario-ending')).toHaveText('$3,500')
  await page.setViewportSize({ width: 390, height: 844 })
  await page.getByRole('button', { name: 'Edit profile & baseline' }).click()
  await page.screenshot({ path: '.verification/edit-profile-mobile.png', fullPage: true })
  expect(await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth)).toBe(false)
  await page.getByRole('button', { name: 'Cancel' }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'Start over' }).click()
  await expect(page.getByLabel('Your name')).toBeVisible()
  await page.reload()
  await expect(page.getByLabel('Your name')).toBeVisible()
  expect(errors).toEqual([])
})
