import { fireEvent, render, screen, within } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { describe, expect, it } from 'vitest'
import App from '../App'

describe('dashboard interactions', () => {
  it('walks through the complete demo and resets all scenario inputs', async () => {
    const user = userEvent.setup()
    render(<App />)
    expect(screen.getByTestId('baseline-ending')).toHaveTextContent('$1,050')
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$1,050')
    fireEvent.change(screen.getByRole('slider', { name: 'Dining' }), { target: { value: '30' } })
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$1,518')
    fireEvent.change(screen.getByRole('slider', { name: 'Subscriptions' }), { target: { value: '40' } })
    fireEvent.change(screen.getByRole('slider', { name: 'Earn extra each month' }), { target: { value: '150' } })
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$2,550')
    await user.click(screen.getByRole('button', { name: 'Add to scenario' }))
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$1,850')
    expect(screen.getByTestId('baseline-ending')).toHaveTextContent('$1,050')
    expect(screen.getByTestId('net-impact')).toHaveTextContent('+$800')
    expect(screen.getByTestId('breakdown-total')).toHaveTextContent('+$800')
    await user.click(screen.getByText('View monthly forecast'))
    const table = screen.getByRole('table')
    expect(within(table).getByRole('row', { name: /November 2026/ })).toHaveTextContent('$1,025')
    expect(screen.getByText('$150 short')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Reset scenario' }))
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$1,050')
    for (const slider of screen.getAllByRole('slider')) expect(slider).toHaveValue('0')
    expect(screen.queryByRole('button', { name: 'Remove one-time expense' })).not.toBeInTheDocument()
    expect(screen.getByLabelText('Target savings ($)')).toHaveValue(2000)
  })
  it('validates expense drafts, supports zero, and removes an applied cost', async () => {
    const user = userEvent.setup(); render(<App />)
    const amount = screen.getByLabelText('Amount ($)')
    fireEvent.change(amount, { target: { value: '-10' } })
    await user.click(screen.getByRole('button', { name: 'Add to scenario' }))
    expect(screen.getByRole('alert')).toHaveTextContent('Enter an amount')
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$1,050')
    fireEvent.change(amount, { target: { value: '0' } })
    await user.click(screen.getByRole('button', { name: 'Add to scenario' }))
    expect(screen.getByText('A $0 expense has no effect on your forecast.')).toBeInTheDocument()
    fireEvent.change(amount, { target: { value: '700' } })
    await user.click(screen.getByRole('button', { name: 'Add to scenario' }))
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$350')
    await user.click(screen.getByRole('button', { name: 'Remove one-time expense' }))
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$1,050')
  })
  it('updates goals and retains a valid forecast while an input is empty or invalid', () => {
    render(<App />)
    const goal = screen.getByLabelText('Target savings ($)')
    fireEvent.change(goal, { target: { value: '500' } })
    expect(screen.getByText(/You’re projected to beat this goal by/)).toHaveTextContent('$550')
    fireEvent.change(goal, { target: { value: '' } })
    expect(screen.getByRole('alert')).toHaveTextContent('Showing the last valid goal')
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$1,050')
    fireEvent.change(goal, { target: { value: '0' } })
    expect(screen.queryByRole('alert')).not.toBeInTheDocument()
    expect(screen.getByRole('progressbar')).toHaveAttribute('aria-valuenow', '100')
  })
  it('shows finite negative balances and a neutral shortfall message', async () => {
    const user = userEvent.setup(); render(<App />)
    fireEvent.change(screen.getByLabelText('Amount ($)'), { target: { value: '1000000' } })
    await user.click(screen.getByRole('button', { name: 'Add to scenario' }))
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('-$998,950')
    expect(screen.getByText(/This scenario dips below/)).toBeInTheDocument()
    expect(document.body).not.toHaveTextContent(/NaN|Infinity|undefined/)
  })
})
