import { fireEvent, render, screen } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import App from '../App'
import { demoProfile, loadProfile, saveProfile } from '../lib/profile'
import { expenseCategories } from '../types/finance'
import { categoryLabels } from '../lib/simulator'

beforeEach(() => localStorage.clear())
afterEach(() => vi.restoreAllMocks())
describe('setup and editable profiles', () => {
  it('asks questions, validates inputs, reviews totals and personalizes the saved dashboard', async () => {
    const user = userEvent.setup(); render(<App />)
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    expect(screen.getByRole('alert')).toBeInTheDocument()
    await user.type(screen.getByLabelText('Your name'), 'Sam')
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    fireEvent.change(screen.getByLabelText('Monthly take-home income ($)'), { target: { value: '2000' } })
    fireEvent.change(screen.getByLabelText('Current savings ($)'), { target: { value: '500' } })
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    for (const category of expenseCategories) fireEvent.change(screen.getByLabelText(`${categoryLabels[category]} ($)`), { target: { value: category === 'housing' ? '1000' : '0' } })
    await user.click(screen.getByRole('button', { name: 'Continue' }))
    expect(screen.getByRole('heading', { name: 'Sam’s starting point' })).toBeVisible()
    await user.click(screen.getByRole('button', { name: 'Open my sandbox' }))
    expect(screen.getByRole('heading', { name: /Sam’s financial sandbox/ })).toBeVisible()
    expect(screen.getByTestId('baseline-ending')).toHaveTextContent('$6,500')
    expect(screen.getByRole('slider', { name: 'Dining' })).toBeDisabled()
    expect(loadProfile().profile?.name).toBe('Sam')
  })
  it('edits and cancels without losing the scenario or goal, then resets only the scenario', async () => {
    saveProfile(demoProfile()); const user = userEvent.setup(); render(<App />)
    fireEvent.change(screen.getByRole('slider', { name: 'Dining' }), { target: { value: '30' } })
    fireEvent.change(screen.getByLabelText('Target savings ($)'), { target: { value: '2500' } })
    await user.click(screen.getByRole('button', { name: 'Edit profile & baseline' }))
    fireEvent.change(screen.getByLabelText('Your name'), { target: { value: 'Ignored' } })
    await user.click(screen.getByRole('button', { name: 'Cancel' }))
    expect(screen.getByRole('heading', { name: /Alex’s financial sandbox/ })).toBeVisible()
    await user.click(screen.getByRole('button', { name: 'Edit profile & baseline' }))
    fireEvent.change(screen.getByLabelText('Your name'), { target: { value: 'Jordan' } })
    fireEvent.change(screen.getByLabelText('Dining ($)'), { target: { value: '400' } })
    await user.click(screen.getByRole('button', { name: 'Save changes' }))
    expect(screen.getByRole('heading', { name: /Jordan’s financial sandbox/ })).toBeVisible()
    expect(screen.getByTestId('baseline-ending')).toHaveTextContent('$210')
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('-$510')
    expect(screen.getByLabelText('Target savings ($)')).toHaveValue(2500)
    expect(screen.getByRole('slider', { name: 'Dining' })).toHaveValue('30')
    await user.click(screen.getByRole('button', { name: 'Reset scenario' }))
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('$210')
    expect(loadProfile().profile?.monthlySpending.dining).toBe(400)
    expect(screen.getByLabelText('Target savings ($)')).toHaveValue(2500)
  })
  it('starts over only after confirmation and removes the saved setup', async () => {
    saveProfile(demoProfile()); const user = userEvent.setup(); render(<App />)
    const confirm = vi.spyOn(window, 'confirm').mockReturnValue(false)
    await user.click(screen.getByRole('button', { name: 'Start over' }))
    expect(screen.getByTestId('baseline-ending')).toBeVisible()
    confirm.mockReturnValue(true)
    await user.click(screen.getByRole('button', { name: 'Start over' }))
    expect(screen.getByLabelText('Your name')).toBeVisible()
    expect(loadProfile().profile).toBeNull()
  })
  it('keeps the app usable if storage is unavailable', async () => {
    vi.spyOn(Storage.prototype, 'getItem').mockImplementation(() => { throw new Error('blocked') })
    vi.spyOn(Storage.prototype, 'setItem').mockImplementation(() => { throw new Error('blocked') })
    const user = userEvent.setup(); render(<App />)
    await user.click(screen.getByRole('button', { name: 'Try Alex’s demo' }))
    expect(screen.getByTestId('baseline-ending')).toHaveTextContent('$1,050')
    expect(screen.getByText(/browser could not save/)).toBeVisible()
  })
  it('clamps an existing income decrease when income is edited and retains cents', async () => {
    saveProfile(demoProfile()); const user = userEvent.setup(); render(<App />)
    fireEvent.change(screen.getByLabelText('Monthly income change ($)'), { target: { value: '-500' } })
    await user.click(screen.getByRole('button', { name: 'Edit profile & baseline' }))
    fireEvent.change(screen.getByLabelText('Monthly take-home income ($)'), { target: { value: '123.45' } })
    await user.click(screen.getByRole('button', { name: 'Save changes' }))
    expect(screen.getByRole('slider', { name: 'Change monthly income' })).toHaveValue('-123.45')
    expect(screen.getByLabelText('Monthly income change ($)')).toHaveValue(-123.45)
    expect(screen.getByTestId('scenario-ending')).toHaveTextContent('-$8,850')
  })
})
